services:
  sb-app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "docker-app"
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=SpringMongoDB
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=user1
      - SPRING_DATA_MONGODB_PASSWORD=user1
      - SPRING_DATA_MONGODB_DATABASE=people-db
    ports:
      - 8080:8080
    networks:
      - spring-network
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    hostname: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - 27070:27017
    networks:
      - spring-network
    command: ["--bind_ip", "0.0.0.0"]
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  spring-network:
    name: ${NETWORK_NAME}
    external: true