services:
  sb-app:
    depends_on:
      mongodb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "spring-app"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://user1:user1@mongodb:27017/people-db?authSource=admin
      - SPRING_APPLICATION_NAME=SpringMongoDB
    ports:
      - 8080:8080
    networks:
      - spring-mongo-network
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGODB_HOST=mongodb
      - MONGO_INITDB_ROOT_USERNAME=user1
      - MONGO_INITDB_ROOT_PASSWORD=user1
      - MONGO_INITDB_DATABASE=people-db
    ports:
      - 27017:27017
    command: [ "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - spring-mongo-network
  mongodb-express:
    depends_on:
      mongodb:
        condition: service_healthy
    image: mongo-express
    container_name: "mongo-express"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user1
      - ME_CONFIG_MONGODB_ADMINPASSWORD=user1
    ports:
      - 8081:8081
    networks:
      - spring-mongo-network
networks:
  spring-mongo-network:
    driver: bridge
    name: spring-mongo-network